---


- name: Set Forks directory facts (part 1)
  set_fact:

    forksPrefixDirectory: >-
      /usr/local{% if forksVendorIdentifier is defined %}/{{ forksVendorIdentifier }}{% endif %}
    forksVariableDirectory: >-
      /var/local{% if forksVendorIdentifier is defined %}/{{ forksVendorIdentifier }}{% endif %}
    forksUsersRootDirectory: >-
      /var/local{% if forksVendorIdentifier is defined %}/{{ forksVendorIdentifier }}{% endif %}/lib


- name: Set Forks directory facts (part 2)
  set_fact:

    forksManagingLocalBinaryDirectory: "{{ forksManagingHomeDirectory|default('/root') }}/.local/bin"

    forksSourceDirectory: "{{ forksPrefixDirectory }}/src"
    forksLibraryDirectory: "{{ forksPrefixDirectory }}/lib"
    forksLibrary64Directory: "{{ forksPrefixDirectory }}/lib64"
    forksNodeBinaryDirectory: "{{ forksPrefixDirectory }}/bin"
    forksLibexecDirectory: "{{ forksPrefixDirectory }}/libexec"
    forksNodeSharedDirectory: "{{ forksPrefixDirectory }}/share"
    forksNodeTempDirectory: "{{ forksPrefixDirectory }}/tmp"
    forksSystemServiceDirectory: /etc/systemd/system
    
    forksSystemCaCertificatesFilePath: /etc/ssl/certs/ca-certificates.crt


...
