---


- name: Load Forks properties
  include_tasks:
    file: properties.yml
    apply:
      tags: always
  tags: always

- name: Load Forks directories
  include_tasks:
    file: directories.yml
    apply:
      tags: always
  tags: always

- name: Load Forks common packages
  include_tasks:
    file: packages.yml
    apply:
      tags: always
  tags: always
     
- name: Load Forks python facts
  include_tasks:
    file: python.yml
    apply:
      tags: always
  tags: always
     

...
